language: node_js
node_js:
  - "8"
install:
  - npm install yarn
  - yarn install
script:
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: docs/.vuepress/dist
  target-branch: master
  on:
    branch: docs